name: Update README - weekly

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  github-activity:
    name: Update Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run script
        run: node ./scripts/src/index.mjs
        env:
          PROCESS_CONSUPTION: HIGH

          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          LAST_FM_USERNAME: ${{ secrets.LAST_FM_USERNAME }}
          LAST_FM_API_KEY: ${{ secrets.LAST_FM_API_KEY }}

          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_API_KEY: ${{ secrets.GH_API_KEY }}

          STEAM_USER_ID: ${{ secrets.STEAM_USER_ID }}
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          