name: Update README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-activity:
    name: Update Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run script
        run: node ./scripts/src/index.mjs
        env:
          WAKATIME_AUTH: ${{ secrets.WAKATIME_AUTH }}
          LAST_FM_AUTH: ${{ secrets.LAST_FM_AUTH }}
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
          STEAM_AUTH: ${{ secrets.STEAM_AUTH }}
